server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Auth - all /auth/* goes to gateway
    location /auth/ {
        proxy_pass http://minipaas-api-gateway-1:8000/api/auth/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /auth {
        return 301 /auth/;
    }

    # Deployments
    location /deployments/ {
        proxy_pass http://minipaas-api-gateway-1:8000/api/deployments/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    # Repos
    location /repos/ {
        proxy_pass http://minipaas-api-gateway-1:8000/api/repos/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    # Metrics
    location /metrics/ {
        proxy_pass http://minipaas-api-gateway-1:8000/api/monitoring/metrics/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    # Logs
    location /logs/ {
        proxy_pass http://minipaas-api-gateway-1:8000/api/monitoring/logs/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    # Health
    location /health/ {
        proxy_pass http://minipaas-api-gateway-1:8000/api/monitoring/health/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    # Containers
    location /containers/ {
        proxy_pass http://minipaas-api-gateway-1:8000/api/monitoring/containers/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
