apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-scanner
  namespace: minipaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-scanner
  template:
    metadata:
      labels:
        app: security-scanner
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: security-scanner
        image: ghcr.io/carbon14-48/minipaas-security-scanner:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: minipaas-config
        - secretRef:
            name: minipaas-secret
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: trivy-cache
          mountPath: /root/.cache/trivy
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1"
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: trivy-cache
        hostPath:
          path: /tmp/trivy-cache
          type: DirectoryOrCreate
