apiVersion: v1
kind: Secret
metadata:
  name: minipaas-secret
  namespace: minipaas
type: Opaque
stringData:
  DATABASE_URL: "postgresql://minipaas:minipaas@postgres:5432/minipaas"

  JWT_SECRET_KEY: "change-me-in-production"
  REFRESH_TOKEN_SECRET: "change-me-in-production-refresh"

  GITHUB_CLIENT_ID: "Ov23liM7bZfzXolwuhcf"
  GITHUB_CLIENT_SECRET: "6ad49fc3de6ebd46476a01cb8517898b6936bc42"
  GITHUB_REDIRECT_URI: "http://localhost:8080/oauth/github/callback"

  POSTGRES_PASSWORD: "minipaas"
  POSTGRES_USER: "minipaas"
  POSTGRES_DB: "minipaas"

  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
