apiVersion: v1
kind: Secret
metadata:
  name: minipaas-secret
  namespace: minipaas
type: Opaque
stringData:
  DATABASE_URL: "postgresql://minipaas:minipaas@postgres:5432/minipaas"
  JWT_SECRET_KEY: "change-me-in-production"
  REFRESH_TOKEN_SECRET: "change-me-in-production-refresh"
  GITHUB_REDIRECT_URI: "http://localhost:8080/oauth/github/callback"
  POSTGRES_USER: "minipaas"
  POSTGRES_PASSWORD: "minipaas"
  POSTGRES_DB: "minipaas"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
