apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-service
  namespace: minipaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-service
  template:
    metadata:
      labels:
        app: build-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: build-service
        image: ghcr.io/carbon14-48/minipaas-build-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: minipaas-config
        - secretRef:
            name: minipaas-secret
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        livenessProbe:
          tcpSocket:
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
