apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  namespace: minipaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-service
  template:
    metadata:
      labels:
        app: deployment-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: deployment-service
        image: ghcr.io/Carbon14-48/minipaas-deployment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: minipaas-config
        - secretRef:
            name: minipaas-secret
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
